### ISSUE TITLE
Manage repos through CLI

### ISSUE THREAD

**Issue by kevb** [swarm-pack/swarm-pack#17]
This would effectively edit the config file at `~/.swarm-pack/config.yml` using CLI commands.

Suggested commands:

`swarm-pack repo add <name> <url>` - add a new repo with name & github URL. This could also validate that the repo can be accessed.
`swarm-pack repo rm <name> || <url>` - remove a repo entry by either name or URL.

**Comment by vudknguyen** [comment]
Agreed, it is a good feature to help manage repository

I would suggest also the command to list all current repo

```swarm-pack repo ls```

**Comment by kevb** [comment]
Looks good!
